# Generated by Django 5.0.2 on 2024-03-13 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_app', '0004_favouritepaper_publication_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritepaper',
            name='publication_info',
        ),
        migrations.RemoveField(
            model_name='favouritepaper',
            name='research_question',
        ),
        migrations.RemoveField(
            model_name='favouritepaper',
            name='snippet',
        ),
        migrations.RemoveField(
            model_name='favouritepaper',
            name='title',
        ),
        migrations.RemoveField(
            model_name='favouritepaper',
            name='url',
        ),
        migrations.AddField(
            model_name='favouritepaper',
            name='personal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('research_question', models.CharField(max_length=255)),
                ('publication_info', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('citation_count', models.IntegerField(blank=True, null=True)),
                ('favourited_by', models.ManyToManyField(blank=True, related_name='favourite_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favouritepaper',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='ra_app.article'),
        ),
    ]
