# Generated by Django 5.0.3 on 2024-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_app', '0005_remove_favouritepaper_publication_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='snippet',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='citation_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='research_question',
        ),
        migrations.RemoveField(
            model_name='favouritepaper',
            name='personal_notes',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.CharField(default='Unknown Author', max_length=255),
        ),
    ]
